[package]
name = "file_manager"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.23.2"
tui = "0.18"
clap = "3.1.18"
dns-lookup = "1.0.8"
ssh2 = "0.9.3"